name: 项目自动化打包和部署
on: 
    push:
      branches: [ master ]

jobs:
  npm-build:
    name: 项目自动化打包部署
    runs-on: ubuntu-latest

    steps:
      - name: 读取仓库内容
        uses: actions/checkout@v4
      
      - name: 安装依赖
        run: npm install

        # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'

      - name: 运行publish命令 (其中prepublish 包含了test测试命令、eslint 检查命令和 rollup 打包命令)
        run: npm publish
        env:
          # 刚刚设置的 NPM_TOKEN
          NODE_AUTH_TOKEN: ${{secrets.NPM_ACCESS_TOKEN}}

